version: '2'


services:
 
 mysql:
  image: mysql:${MYSQL_VERSION}
  command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
  container_name: ${MYSQL_CONTAINER_NAME}
  restart: always
  ports:
   - ${MYSQL_PORT_LOCAL}:${MYSQL_PORT_DEFAULT}
  environment:
   MYSQL_ROOT_PASSWORD: ${MY_MYSQL_ROOT_PASSWORD}
   MYSQL_USER: ${MY_MYSQL_USER}
   MYSQL_PASSWORD: ${MY_MYSQL_USER_PASSWORD}
   MYSQL_DATABASE: ${MY_MYSQL_DB}
  volumes:
   - ./mysql/db:/var/lib/mysql
   - ./mysql/log:/var/lib/log
  networks:
   - database
networks:
 database:
